name: Azul
favicon: null
layout_spectrum: 0.34764704620465636
typography_spectrum: 0.9860109509900212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.814299174118787
  lightness: 0.8348368287552148
  saturation: 0.09368590055964887
  rhythmicContrast: 0.16660064761526883
purpose: []
